version: "2"
services:
    # Web Server
    web:
        build:
          context: .
          dockerfile: docker/Dockerfile-web
        command: "php bin/console server:run 0.0.0.0:80"
        ports:
            - "9406:80"
        volumes:
            - ./:/data
            - app-var-cache:/data/var/cache
            - app-var-sessions:/data/var/sessions
            - app-var-logs:/data/var/logs
            - app-vendor:/data/vendor
            - app-node_modules:/data/node_modules
        links:
            - db
            - redis
        working_dir: "/data"
        environment:
            APPLICATION_ENV: dev

    # Command Line Tools
    cli:
        build:
            context: .
            dockerfile: docker/Dockerfile-cli
        volumes:
            - ./:/data
            - app-var-cache:/data/var/cache
            - app-var-sessions:/data/var/sessions
            - app-var-logs:/data/var/logs
            - app-vendor:/data/vendor
            - app-node_modules:/data/node_modules
        links:
            - db
            - redis
        working_dir: "/data"

    # Database
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
        ports:
            - "4407:3306"

    # Redis
    redis:
        image: redis:latest
        ports:
            - "4408:6379"

volumes:
    app-var-cache:
    app-var-sessions:
    app-var-logs:
    app-vendor:
    app-node_modules:
