parameters: ~

services:
    _defaults:
        autoconfigure: true

    demo-achievement-01:
        class:  Yay\Component\Engine\AchievementValidator\Validator\ExpressionLanguageValidator
        arguments:
            - achievement.getName() in ['demo-achievement-01'] and filteredPersonalActions.count() >= 5

    demo-achievement-02:
        class:  Yay\Component\Engine\AchievementValidator\Validator\ExpressionLanguageValidator
        arguments:
            - achievement.getName() in ['demo-achievement-02'] and filteredPersonalActions.count() >= 10
