services:
  # Query parameter converter
  request.paramconverter.querystring:
    class:  Yay\Component\HttpFoundation\Request\ParamConverter\QueryStringConverter
    tags:
      - { name: request.param_converter, converter: QueryString }
  # Header field converter
  request.paramconverter.headerfield:
    class:  Yay\Component\HttpFoundation\Request\ParamConverter\HeaderFieldConverter
    tags:
      - { name: request.param_converter, converter: HeaderField }